name: transformers_from_scratch
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - matplotlib=2.2.2
  - pytorch
  - torchvision
  - pip
  - pytest == 6.0.1
  - sphinx == 3.1.2
  - jupyter
  - jupyterlab
  - pip:
    - mlflow>=1.0

