name: transformers_from_scratch
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision
  - pip
  - jupyter
  - jupyterlab
  - tensorboard
  - pip:
    - torch==1.6
    - mlflow>=1.0
    - torchtext==0.7

